apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.config.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: user-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-db-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: user-service-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cloudmart/rds/user-service
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: cloudmart/rds/user-service
        property: host
