image:
  repository: 378780514485.dkr.ecr.us-east-1.amazonaws.com/cloudmart/notification-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/378780514485/cloudmart-orders"
  awsRegion: us-east-1

serviceAccount:
  irsaRoleArn: ""

namespace: cloudmart-prod
