namespace: cloudmart-staging
replicaCount: 1
image:
  tag: "5cfd002edaa6ca9cbd05855abaa9f9d578f74805"
serviceAccount:
  irsaRoleArn: "arn:aws:iam::378780514485:role/cloudmart-notification-service-role"
