namespace: cloudmart-staging
replicaCount: 1
image:
  tag: "4bf131ae34c4b5fcebe8a248ca436bd238a94335"
serviceAccount:
  irsaRoleArn: "arn:aws:iam::378780514485:role/cloudmart-notification-service-role"
