namespace: cloudmart-staging
replicaCount: 1
image:
  tag: "e7bac2497d890c3b0854906a0130203516a9c690"
serviceAccount:
  irsaRoleArn: "arn:aws:iam::378780514485:role/cloudmart-notification-service-role"
